/**
 * The five everyday spending categories Drift models.
 * Kept intentionally small — the prototype optimises for clarity over taxonomy.
 */
export type SpendingCategory =
  | "groceries"
  | "fuel"
  | "dining"
  | "subscriptions"
  | "other";

/** Reward rates as decimals (e.g. 0.02 = 2% back). */
export type CategoryRewardRates = Partial<Record<SpendingCategory, number>> & {
  /** Fallback rate applied to any category without an explicit rate. */
  base: number;
};

export interface RewardsCard {
  id: string;
  name: string;
  issuer: string;
  annualFee: number;
  rates: CategoryRewardRates;
  highlight: string;
}

/** Annual spend by category (in AUD). Every category is always present. */
export type SpendingSummary = Record<SpendingCategory, number>;

/** Monthly spend by category (in AUD). Every category is always present. */
export type MonthlySpending = Record<SpendingCategory, number>;

export interface CardRewardEstimate {
  card: RewardsCard;
  grossAnnualRewards: number;
  netAnnualRewards: number;
}

export interface CategoryOpportunity {
  category: SpendingCategory;
  label: string;
  monthly: number;
  annual: number;
  /** Estimated annual rewards value generated by this category alone. */
  annualReward: number;
}
